//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWorkerSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Delivery_Log
    {
        public int Log_ID { get; set; }
        public string File_Name { get; set; }
        public string PO_Or_Non_PO { get; set; }
        public string Supplier_Name { get; set; }
        public string Supplier_ID { get; set; }
        public string Sender_Email { get; set; }
        public Nullable<System.DateTime> Processing_Time { get; set; }
        public string Invoice_Number { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Perentage { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Bill_To { get; set; }
        public string Status { get; set; }
        public string Error_Detail { get; set; }
        public string WorkDay_ID { get; set; }
    }
}
