//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWorkerSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonPO_Line_Details
    {
        public int ID { get; set; }
        public string Supplier_ID { get; set; }
        public Nullable<int> Line_Seq_No { get; set; }
        public string Company { get; set; }
        public string Item_Desription { get; set; }
        public string Spend_Catagories { get; set; }
        public string Cost_Center { get; set; }
        public string Project { get; set; }
        public string Custom_Org { get; set; }
        public string Tax_Type { get; set; }
        public Nullable<int> Percetage { get; set; }
        public string Employee { get; set; }
        public Nullable<int> Account { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Updated_on { get; set; }
        public string Uodated_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
