//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWorkerSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonPO_Line_Details_Default
    {
        public int ID { get; set; }
        public string Company_ID { get; set; }
        public string Cost_Center { get; set; }
        public string Spend_Category { get; set; }
        public string Custom_Org { get; set; }
    }
}
