//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWorkerSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Details
    {
        public int ID { get; set; }
        public string Supllier_ID { get; set; }
        public string PO_ID { get; set; }
        public Nullable<int> PO_Line_Seq { get; set; }
        public Nullable<decimal> Po_Amount { get; set; }
        public string Cost_Centre { get; set; }
        public string Spend_Catagory { get; set; }
        public string Custom_Org { get; set; }
    }
}
