//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWorkerSample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkDay_Resourse_ManagementEntities1 : DbContext
    {
        public WorkDay_Resourse_ManagementEntities1()
            : base("name=WorkDay_Resourse_ManagementEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NonPO_Line_Details> NonPO_Line_Details { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<NonPO_Line_Details_Default> NonPO_Line_Details_Default { get; set; }
        public virtual DbSet<PO_Details> PO_Details { get; set; }
        public virtual DbSet<Invoice_Delivery_Log> Invoice_Delivery_Log { get; set; }
    }
}
